network:
  version: 2
  ethernets:
    enp6s18:
      dhcp4: true
      nameservers:
        addresses: [1.1.1.1, 192.168.2.16, 192.168.2.4]
      dhcp4-overrides:
        use-dns: false
        use-domains: false
