---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-insights-token
  namespace: monitoring
spec:
  encryptedData:
    CF_ACCOUNT_ID: AgB5tr5ncvMcp3ifYhztSsOEnGWZq9wL5jqNLY/Q6qZ6xegS5aSGWl9+/GO470dAvJR2LnymQcuh7rXo7RZl579eRuZjvpAPqSX2nFhRa0uFkCoE53uAP9k+IvMqYcYMWMdA8uK8/+fPOoN0MiWn9shbeR8/usoCjmoZoUxEJ2Tz8y0+HqY+KqGgVg/yuOKFIgBItD97nJm/6b5Q1XtML4v8Hh8e0CLiwV1XQ7Fjy1iw+V4OxLzufIzZsMZKAmz78Cv/FSlig1o3bcOQoM3kGaDgslbjlV5DoY3dPslc581Q8holR1HQC/QSKQ5QRm9zgXxVV71sLJisOqviUQy5UGo9WywaC0dNHlxEjmupnsIyiiuA0pNHNVpART01DoJFRzyzamllbcJas9Qug7ysuecnDwW6P1pQU+MXgLz3yHe4PYv1bCItvlN2llH5TGYqVbnWARAdWE5k+VTxS7OYDzQBB1l41GcHimH7gJ87BpO9iigC9ze23qEeAQlUjh1eni276JmBGv4DybohgxzNYlrLL0D4W81sfGsn/8XQLMCdZVF8KnleG9cS+t25Wum9yNYSAcMomE5JwUxp8hoqGLXckoUnLZYaXfTwClBGveIvE78FHJkvfhiSbce8sPmnT582SGnFwAUoLsSxGs2bcPvc2OrC7uROWswWq9ZAe5jaHNVpEqNbjqZGW5aXyRhxIfE0hEX2tOgfm2EpqrQnLXshdehbJPsAxi31ZtUsnuO8Tg==
    CF_API_TOKEN: AgB6NaocdSVeASsCs884LRoX0+VeqzwuU3dskVzgF/YipPVxUSPYJVV2IMVfEmYR0U2uahHBtmdtdQvyqUjEA8g5R9L2RLvPraHu/cxoC+sc03DEMacL+kkFTpT/8FoLWXT40jeySxmzFnyeqdtd1NtQCF1Z5d2psKHY2xCSHK2iq06vSoAmfTaEvfN7vfdfQbJP/KGeEa+p9He2tEGnwSMBO7xDK12PGfKD+Dm2aaifylMrOBqLbUeBJQQoyCE9NBn7yxy8UXkez3QfbAwk6KnumZkv51/qbhFQu7KylA3m0Fpd9Zgp89JncHOaHEQM3BL7ohMwwuD/Bd7D4CmVSWS7nM0mmTRJ9tMx2vFy/kH+yx9V+FMi9gscDIp+/h01fU5E52DCzcU1xK2MrWOEnrTCWnyLR+wwaeH+PO5cHb9Tbkv2kx3jdNVipEGf08t2v9eNUmTCJIMYd7pvIXhKxRniPv7ZRL91WLnIyqQe6KPidVsHfHDlHnAsforZ046C9TNKBTaIdVN5qb0Sg5ogwgpymYfPl1W4+6TO9pKUc7qrHG87DUaPLwexbEu6He1ls2Vxq00y3m+FuYxiOiYis6jBIfC4wISCuG9/qREXMMwR/fCepH7W3fYgp5oRxSAhfEaobi0s8xQ9BQqzuBtJTpdz93PoDISkQ9SslQ/rUarf7E7gQ9VOqrRNiL78XT/GnscLeElagSVhR1dXS8QshSsZ7rkVCm4sW+c0Ft2qsqUdtn5a3S1sVq25ZsZz09vY52GkUVodEw==
  template:
    metadata:
      name: cloudflare-insights-token
      namespace: monitoring
    type: Opaque
