---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-notifications
  namespace: monitoring
spec:
  encryptedData:
    healthchecks-ping-url: AgAfxzJnQ4mT8975dc66fLP4gXOvS3Sa4b3KKaN2XxOMvrBesKDV/Qu4tnW3CZ1oWCyom+apsnvweAjN1N68Xa1CqKFyUJZrRMil/mo0ZWRMdYcUXDAUBySVC2PO67o2y+KQ7wMnKIlvblxm1fXJEBaCVPB8KMyw+FIiG69QEaXzjyh9Nzp52pa8+xPfQymjJNh5wANqZOpHzswHCXnh74YTMFxlsRite0rcQeeypnVv+2UtmcSxg3E2wgdQ/gG7XfSlVbXAQgGQnoKExG/nMDiMc8muzPRvl5nhCVdwU3cxtZaGPbeJGtnfxEPMLGuvu+JwoiqXbCT6BzxRysJusGldrF7CPLDjv88BCNjtspy5BZPKcSKf71VLotNZNcQK86XtJGxlQwixlcyPRsoyiyhP87pFW3v8+kwCASS9EOPOLrFzKm0NkxRRcsmyCRNhF1RFSzOXi09QeAm/3m+l3g68TwBcMUSZAYroOS7kNwKf3HjmdBr7lXVeN5yxTSdMBssbkYb8zOp4o+RgNG/jnOEit/7wBWllFF1kuLm/6318QrbdCxAWZ+4zNVttpCxLYsM1oVHBgjnAIAMUReFNSmvMgsoV366Doob8AbqVwxZS2c4E0RIbIm8b3r7bBbpQzcjlabqNXHQUALKGMGyxJh/H97H3q/4pp/8yq3vsIIID4/p3MiI8bl0dHHUo6JvTEJeGUc/9T1TUPxs+9QUI8wicpBce5ieGNiIOfLWRdSyZ52Wwd3ta+viw+SCjA8fY0vm6Wdsa56b94g==
    telegram-bot-token: AgB3JdZHILVDjU7F2CsgzN0B6kxYwslQ4Bd3gae0IKbep6jGoysZD3FQn8Y6EBrCzhZm7RzCbY59V3dqlyMlGKElBtIsmNIsB1alXHYdXkjT7TgEMdT/7RqReo7BVOs4hpeL2dhDxtPqJVr7fSem5A03DZYYdF2GsYbC1cXDWFol0tvJ1OYMMkoAhxTcb/XN+bNxrgRlkxiziJ7PUqKli8uJi1QxuhMbcHyJxhO2VcYBFI3nRGf4bB+v5nZWaLutXZgws940DasakPkJE8r+485n0GzJUo+GkKDEMCkxGbwadHA6xk7u/YtW0zrLD5PM+5mZ6F9N7PyelUtvuTZbl2d3nIGQ4623vb+UQSLAqGxTozqWLeBiSk2BVGDAeRxZ9R93jK7vTS1c8M0LkS9wYy50+MQyUwJJ/yHeZhb3BWrPmIDiJdrkrWrGI8p0lfaNPoOwr/Fr2kIbzm2Pudt0AxaHS9aiJ2nSzSmH0xyD8QZUbmjytJX0/dqxsqC81RbcctWyL8K2ZJuPucOFGRsiOO013LFtr/Scdq5JQUdqmGxiyGS8+LzKlou4kAUA9k283GG038BUHNa7Qq1DWiVkMP7JNRNMSuwCsyJXQEo/D8zIuoKnv94LAm9LPyJ+jBT9hHsQp9X7iJVNOgYPRvVa96DFOvUhSO+7L63bxmtvsUxsZZ3ui1TekdlK/ytt1iRtVQrSgS47UEFG8pRuBarP+iVImayz4GSNkaFXO6oCFHNKx9PMdUepmEQiKc6kPVKa
  template:
    metadata:
      name: alertmanager-notifications
      namespace: monitoring
    type: Opaque
