---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBBaaXNQR0PneJODtMxsaaqJAziWSQPCC+thSF/SZdHl9KKbv9/H6IWDhXr1G8XYkWFFSKqenLXLF9l75iEn/nwmawgn5U0RbT8vpRUhTg+TjGyrQEQLDVBkRo8NOfzrh8xwe25sh2C3NgzcQ64c0nk7jjkcj9QNejhA+iFxu1aJ5Q0DgSPZbTghpzgoEy4+K75QhDETa4FGOxzBHfJQbLH5Rs1MGs9XZ2xvJU/6/FLMgb/kw7idD21jthklWJY1+rkZQyz+f49KBQ3vKRhd8ugQDcC+J/oN+udsNQaKAF9M80MqjIYHA0RnmTMep4fzcWxZPJK5eCbYhCFxbRQjEIpqTDUEvZEuptBgRrPJvgEz6QMo144iMhD8jjaujgM9AHFbVDeF/39trun9XXMkeFJLr+hqfuu1KN4tkfHFGcLswIFmvxdBtI2jLRK7AnPADs8DRGe2f2H/N1v4+k9VHkuaeKVfMlA6GaXOB6aGFWJt+Syp6f251+IPAswihgQcdRKYFgTufqLqJaB/Qs8n5vZSgqRAF4l5+5Q6CAmn9n1rNhWRnAAfFmy5dHrWZf1bWtuUzCzZ46jiEruI4N1DdVNIX6VrtwWW9OtVVBcKyVlqdSjm9mqECUZ2GB0z9Oac7uLW9kZMOmpu9YyDMKq2y0QdQjuhVa8/64z6HHYlTwvxcYnAEcSuGLqc+cfF5Gd6hfYdg7auztBZK1fsEAT91Zrub0KruDRiZSbbEdS
    admin-user: AgAlQSofviB2TSZ+FkLwdIttaAqtY1tUYwdTfhYfctSdprjHNk2hUIyo3JgGKJNs7LQZkRQcmBwKmu1fWVJtCsKGb61EnVIC9bH8OvIDVHk0kNo1V97ahLYRK+DeJJbdLHVaaoLcyNdwbMfy7XLJIijk+GaOcqQfNEgj7tMpJ9jx0Wk7LtYxiiNu9FPfPSPaxK/Su6JgjaHKBBb/TSrSuasecjZAI8cUC0lLphzCXdarsp4mb40h4cFtic+h6st9Dli+zBRNFvJ4CLK+UicrXlh77wGkCrC2xxRMhNvUaKMFvXf+tVSIBadWaiZ5/crW1c9CsGdl7xX5TPW/2xWr6JQPQsITWMHoO3weFFfdPdgvD9EtrmgGAM5su/+Guukwz12b85m3YwpUrbzImeHR7e5SXcFwozo2clPGs7MtRcQTiFkoMv7xFpUnD+57PqQoZFskCLVrVrHsPzvmgXLdnUKQ1KMn4PAHh6FhWiGlcJLrmRNI13W3x33dk9nl9OLuy/3sbbxW3LdCv6HpYqG4uaJ6qrEb3ymtKs5be2muCGjACKMv+MDzRa16WJuYxVPHE99YnAQm/JqueKIPE0+zJaIxYouPe2PziEDTB1ha2wF63PyI17bjt6nzHmd1cOaTq4fsprO/uWsIZYLVNJOi8BYlIx35IFyC2X7hQFSvxOFQZneaHKTFAxh3wowu85RePuloEXXAkQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
