apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-hub
  namespace: beszel
  labels:
    app: beszel-hub
  annotations:
    homelab.io/expose: "internal"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
  - host: beszel.elmstreet79.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: beszel-hub
            port:
              name: http
