---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: piaware-secret
  namespace: piaware
spec:
  encryptedData:
    feeder-id: AgB6/gK8kKJMx3KKpGif8xz0GhB36zp7b5Eoo+OBdOoRDHkBdIFtXBU9Ze0fIdQmNMwiKFcdGY14cfnReElHHPXXB/0RQxLRA+EFkexvElX+B8SPcD2qe1XDWFsII1cKA4Sm5szh0RtvL5iPv/y+Sd6oDG45Q2w8Y5PiwpIgFfPzFtMlUI+5NNbiGxZPBvfpGXunLha1DlZZgIss76D8COysL88Gn/hy7pjCem6+Nu0IkdpzbqYUMP9fwXRhAk01ebF8w0gnDTJ526DrlYqn4+PQDFhVyccfbfNmXzuuR2IFMREYy8eW8EZ2/uJwxA98fgRn1AQ6U5HJqKABG0XkuxNSOVbEGiq957mD9wxLKev5vR3jFexqZw2zcq0qmaevyGKMx5WW6v0E734pdVHS4TFrp0fGpra7fAw0QvqVs2jKPdzdhsod1VNLWDueQLNdrLStKJ4+0ToiiKVCmrQITqIuCmtfYJjxoTUo5TqIxBTHem6P5BIePyvLLrRTzgVZThOLyCFYnPILoOG68oqTF4oFo+Md+NH9oM7Uk0opoNROgeLU4RcfUB5pRLNUAEBlJP6ng/iiVh0EG/pUQ//T8up6JFRO6Ynzxu04sC7M80vANUPp6oGIU5CiNsyAXqMTXsZeLroQARnNcwztUyY1955w8UIMjeXYJDsM7m6kFfxLoWkDkwaCMSgGvxhrApb7ZVA194CjxxJisdU3I9oD1NRMZCL673r3Rh7aw4hnGFVUDNR4ynQ=
  template:
    metadata:
      name: piaware-secret
      namespace: piaware
    type: Opaque
