---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-homepage-token
  namespace: homepage
spec:
  encryptedData:
    token: AgANucp7qdQ7cdJ/5zivGe/dc2PSDkVA4+Ta4MCR7yDiK0VDqhF3ChQOvlIcZsdra2/gPrkvPxeU7VtMFHMoZBYoiLBz4wlBQkq4NamaHGCwvgOpelz6HrcqL3URpR+Ia523LoY2J4IjjueGC9PItvtvCGV0gb1EITF658YWp/noPS27evgGXZXpr+9Kk95lMzMS+v3DHHZogqa3PvmTrDRoypZFuG7UPVkcENAZjxGSAJbz0CCqstDbrn1aIql4r/PQgwtvowwgYK9wy117N81pR8zTGm+Xovfs4chb9ibJi8GTFaRVWkUm2pPZd1/AhjIDwA9FE/I71mHeLEG9StA8PM2WGxi3VXgaIRaO7C40tdDsmJCyPq1r5dJ1Lqoh/oqiG/zxtglO9mN+uG+TtUyoaZyRjT0288KYnwcxqRl0fCLfHYXESLe8oGWpDdURZtVRPdEEKTALa1rkWJJVPd+81fTjnwStfcSRNNePQzWveLWw/ktUmcjTcn0GGBxhFSTKy7j/M0RLbFoq/iZdRazjQ0UG6Mm3tzWgXv+6xb/kGCt1anHNtAikUPghWqs6NhOzVcnfthBFO+rDBRvevJVD5iYfnYAEqiG3vnCRh1vC38ihwONnttqP9euvjrMj3+wJJaACJGkKNi73EezAl8mCB9qATU4RqF582iufMK+G6zMptBU6+uauAbcxN4+ldjBW085FLJ/TSDSm0jPdjG5VwJmiDgvA1Q+9BdohaOpd2AWEefS2WsXvtQQ7dzFdNFyC5ezPDeZReicbIvTXoV3ga7zQoTB8+53+Mtg3ApC3tBUH4575iKgLYwm2tzAMQktilkxfq4pgof4pJiUdvzY6XIGJoLufOqzBFO/Kn1ZJc2VWTucrEjOLzSjAs1Ylz1bN3OdOZ7gXpvRz/1pCCsvHKS5oF/+0/ZXN0Ru/13E9HP3b9HY/mj/MqtYdDgE1zSkHPssQ7VfuJrNWBuhnzLE+S9iNyeHA8xh55j0E0nAkCPca6ZrQDdMqelsNHLsO9go=
  template:
    metadata:
      name: argocd-homepage-token
      namespace: homepage
    type: Opaque
