---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-grafana
  namespace: homepage
spec:
  encryptedData:
    password: AgCgQdw8Ad7wcvegrUEM0j3Ud8I6+mNyU2pgjLHJ0jZyRAEebK8rY/V9Z8ODH1HJdpT9/TDYlBK0dDGpMl9NqRlPJri70KEqLX/vCPNFB180Io+xtRJIUZxW3xdCdDaeCxdYtDS6E4bhChtjpk/bx3uq75euAHaXj3j30KrHlWWNq5THoS5UJ8iv+ikWyqyhVMPnxlbcqyM1ZGgo4xVdKHItCAlzk1K9ORTTpjz7TtUL3AbJH18YhmUhQYts6GIThSKeZCOD6uo4791hPXr5tpHh1+ccv5xyo4mKWE7i/j8gC7y2yb1VxVO78I0n7CIjigD1Y5BQx3LX+q/lTWQ7D1hNR4bz6mfsDZ2T3Ifi5q4L3q7ZWCcZJe2tEsh0ybcFXl54rzhmKqR2jhlUEOarj6F+YYjkBVk7hR+NYiiZQ1AnAUXxb5TtXCWsJOTFX877f9PymAWHbZXwuOOgJyPVEIpXyFAptIGe4uG6I40KKk4QP095OKXwCAagU0QsIYgRWYAOqSAtROr3frbo6N51jIP9ZN7Q/q8MQYwEjr33ZEKCgll72PDf26NROnYac1ZvexRZ+x/Gn9RW5h/HNIGwuqGfhdWiE9jBTMcYZ4eNHt2IrkEu+/1ogsLNEDZ8279569kCATGkLe2n6czNLryNiMuzvokZcsBH0iOlbFYnJbyIKlNqv3kR75iigZbbiRzFoBR4UXgdOvvYBVXedIztZiRZqgGGdAqjjhi0RElX
    username: AgBvN33vM8jV/BXHWXBONHl+As6dnmzLuuydM7iNua+wG+QDLWWORYmyAufOh6bsktSaTHAgUuPIOpdQc+l4t6PV6HvaRYJNMRobvn7VkbpirJidfBNzTFEIWkJoU+YO6AGr7EM69qh+TaJh3pEFwoAz91nhpJ75cF9lTOJTATr21XxVWIwOI79ODqajlK0Xpl1eNPmHziXrUENZCJwne5PSpNYEVrFV0p9KhsERskyi5KwZPPtCM9Rm8wg6MGC4ohzwrxCOzkeWB6LvvfPYNTNK1kLsfMUyNKANuVupJwGra1UsehtqZ4cqUTbz7hBLjAjlY4bRJ6sRZ523yfV4HD8Es9CXINX90FUeim1lDDX4TK3vzkL2J/AknJhUrvNLLTAQKgcgprSFPEAl2cSgQsXBO8Ba2p3ZAWDSnkCs9n/sS/StCquYZJw9Ljq25/EXvf3WLxJUFJeDu1nhgzKXUmnrOeI87V9antuTKy4aLwj4dd9rWMdjcfQsGbOk9iuuqSM8pUiThlCU8R56wXMWKO7L0+6kpkDFl971p5YnUJACfCuJVFnUMplD9dI8NtinfMtt22XIfGzQmrM88R8qyaCj4GjK38Ljjy0NQM2BuFoG2oZG8ZpVYsUt49tztJuonCJHBuSgIx1pDf9EHVm33/4SwAvyMrK8ulR38fqH71Jq583pjRArHFg+TLwAm5SoAJZeAAovMw==
  template:
    metadata:
      name: homepage-grafana
      namespace: homepage
    type: Opaque
