apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ripe-atlas-etc
  namespace: ripe-atlas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ripe-atlas-spool
  namespace: ripe-atlas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
