apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - nas-cifs-secret-sealed.yaml
  - recurring-backup-jobs.yaml
  - storageclass-nobackup.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - node-config.yaml
