---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-nas-cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: AgAhh9WXaeaUrACUX850gfr2FF5yxwlAQChzsGMFoFRYHl7IMjWxmmuew3pjE2nR91Lklj3aSXsTBjxQRrNQOu2aZtwl8qmUzLBEaW/e0zfhHoDjwmWPBjmlg/uhflEB5wfz4lFsQ/MdWiGlSb+hK64T9s8XL/62nNsGAzMb5Qao7Zay5pTuNdePOueNrlf5oYLfYJzSaQVnhmgzgYoVBbfUg1J9+66FfuZ/GF6yyRz9Srg/2260OhwzKN326ylBhoRwN4wa74bY7ndqSH8+UYy/d0cNiV64wPgvoK5k5lmWt4o7nMt8DqTjtWuHSODQvhwoUuAS8NIdWyt7DSxPnFZRxsMe1FTdwXkNT+uSxinih17CTIMURYQJ9JO5WwWMlc52Bgvc/N5lR0jlUBd9X/HQLhg44Jvpf9yMXkipFi3iuhzrQb7mFOt0sA+VT6jcvYyWMPoLvSGzhAJS9XXe7OiKXomjh8+IJcPA41JvLhG67TAdwhPdRYau0NkYK7RDe02iwpVN9qTm2RBh3uyszoJ1IehpI60UGkkZhHF1UamfsUEZc6SfJkC7A/78zFRc/7gfIJSWqtJE1Et9Qzq2XEV2MbAowGBBcl/x3olAVzIPs5HmYNh6rBw+ooKUf4ngwxBtZi4WItkcX0jSaJl6PJQ+opBHQkTOPgVcLXrGWFaiejDr3S6UJZEB6QOWY0CkmaE6Yz0r1tClQ6iYC0DzdRmS9cNjEw==
    CIFS_USERNAME: AgC3TCjnMXUg8oUYPJWeD3f0wZjH9oGWo7p3OuVcXEcpNqjEGZjKSAyaZODIxiOAPGLIAZSSBhUgh87Q8QcTTOHkksACFiABb/rQuxN8AVbLadgdI4o8qm5oOOagMjauoH2hsdKW3BaMEUNeCUnRP7vXSD555gNbMOQIM3s0uZUSAGIUHRiZa8yY6cGhtwIKwttUG3mpEOs0GSSGNhuIKr+pBRSSDujxWjQop08QLxUMee/JqBBroQ7N6FKW20mUp5V7am/lQR9MINP5O0VoisKOQasFSSzShoe0iW2fW5q0BdShtkZwqZ42rOgbqeICdw3//CCgvTqj0eK46ySY4XI5alg4/koSXYGacJF6X/uMgrbMGPOZf5+1RqAa/oi+EkNlXHEpvEBFZcazVj2w+3LfHbQ4KazpMrdYHbaI5B4B8d4S7Fk4++K2MDAYiICG2WDeIB/v0A19ggi97KpSyKji50za30CXoplINqMnYa9M5L2vrQ1212yjaBtzGbM6ACy7m5RP8eBI8p9QsXpyCYkRDInZlLvq5xlueJsjmS69GvsLXIbppom0k4YyeKBcMEQpShfOKm4QI/CyFxn6WCdlFVdWvPT4mccwTTSjkQnK0AHQgCFPQRW3rgveLNplHwbWB5kgWJCkXqJsFVLuThxWNsDbzuVUzM/y6issw44d4C7FxegVr5x8UwaqcXX421egl/w3VPllyw==
  template:
    metadata:
      name: longhorn-nas-cifs-secret
      namespace: longhorn-system
    type: Opaque
