---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wol-ssh-key
  namespace: home-assistant
spec:
  encryptedData:
    id_ed25519: AgA+C5elMX5+Zn5irQzF3YIOJj84oNLIXVX27tk7PfirmWSWzQ5ReYlxMqvaBXR7wv87CzFpKU6uIXyrCcm3aUOin0BDeHUy9c5YuXub0nrjgbGoJcOxof92ivBgqVIwT3TyI1TFZd8xn5w1PTi5ne6Ye2Y3YFqvZStBjJuQT4Cb3ZcbOsDv/EHR9H5gyJBAjWb2VWW3zv1xJ5+mxFsp8Bb+/l5nRz8zYFQss+xAWpMWddhMYA5v5tOd2dEz6Rf63QcCJ70Gc/HlpLPPZnpIm+xCe939W8sph5Wnsp1k3JI1z7nNRUlp5GqE3NcZ2Yw0ixMAAt5pzJS6qIW0vIHJLhLOW0SKGGbf/w3cMYWBf46ZPvswD5Kv9n4t5lCZtW5J/nAeRIF6um6suMer9rImoWXRwdVWwfweMGqB4kI9tlLPRz8IFvgMyKUj58nJZ62CMfmLS46Xk3gNOBExl71faaxeoGpIjweLk9wCz++gtNSeA9XyY1fMYlrqvRL7uN0aFgulOJ/i1FFWE3jXFysOtjmQtm7QjteOUQXt7meacXn03U5aEff1fXHVtsP7GgrLwcCDXbHwc6rtukChLPq1CuUN60PmKhqULv38SsrKcuYqwWaChYCf8FWDzIDjQvrhasbjf1rAOs49jOhgwlJ0gJ/v/oVpAeECRCmn6JxuFDnIMx7N/mEeBr2q5RtuWUARjc0NT3HF51eOhggnZ1KA2laYmePUAmB6aSX56XpYFLKCJbwzVGmxQjM43yUHLLWts75MVxeOqGDxXCotyMjDQ38OvedkAoGQqW9T32+onZVWhYdSNh290Htq7uSL6CQBZd49o2gLG0CQ5jPapIGabohUD4ekfLaLWeHkDWzN28Khq2OHXKhFhJdshGox2jN0+0fXjmOZzrdkS7+EAOeEVsoKKG+8OvOls8nxSRncPD1srtw/l/2gDYcxrZexsjFbsseaOot6e3ffZ/mNwE3SYU5LljoVl7U5nS7FFDd+Ba3AdZJ2Copx4YNoZv1ldhHaPrSJus3gggdLjROuoyH/P0zR9B+on/PCH3NpBFx5bRJdoorVhuiQrD+PLgWSOduu/3IHasJbOcPs/Ws4VrKdvm9k1Nf4mla/bP75BMXrNsYCgf1c6PvRsmiVHSuqkuVAiRtpmS70cOOvwe2CCUNyS7APFbdDN+EfMQAmnG9m4L6cADitUZg0EWj6EWBwGobPQNdWrV7RWP2sSRYUeDx7csQFSEUbbJbMsrr8WfvWENFlPIVSHMF4TT5JDHl97C3Qs8M=
  template:
    metadata:
      name: wol-ssh-key
      namespace: home-assistant
