---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: feeder-uuid-secret
  namespace: adsb
spec:
  encryptedData:
    uuid: AgAHycpbNmFDvRB+lwS9XiWPP5XC60XIppq+XUZLmtvvF3rckXvQJ06dP/bSPamD8TZkJv0Iy700zNZsjO3ctjs9tZ+agZMVyemmR+DYtRFaaM1ujo0rU1g+q5ygaBLfDfb73sZuqQI2PYYNwK/7ttsHyxxOUnyh95gDwCe6vVr/lJLlszYbk8HFyAGMV7ykXfWVv0UJntD6r+OuUUlyTujzsXtXeLLXlbwywyTzb747uS3oxeDsR01lUef8CMyKF3ErN/YhVKdun915pIsAZ8oPS7qz9o29w8mTVXsBl9AAeRHTZOju9HHG+oHTIiYTIXiArM0M3rBJMxg5T52u8TjwjhI1HmJmQGIDUj5foGfRL/CvGKOMr1dBjsb3MXbxz4Bp8DoOR4gkwV5OPpjFmJ2ZgqPXa9QQNNIXU2f9ecQBm5AfqCyhu3pptwwT8ja5D3xo1Uhl6uiGQCCwYTepgkhZ1Ts0atMJ7cSa9RphXkjh7rzsFc6gqiPRSsbaZjtup3treED66iwDKzWN3YfLzh+lPF1xlIC30Hw+zDrd06R3rzLgK1GDekTbqHNhfNmwgAFfmH6Hvc97gUuNA9rekRpPYs1Ecl8EpIvOl4J+8yOI8VSoIRb3RBH5cObmXMZgFA+gneHdpHiIdvWmdUFeiW06AAGUwGn1b/J9E7cXnXrWDh3Fjct4GWmGbQURym62ek1WL93CzW2Ppy5Vm47wNWmsmpRTJXAllwp6AvTBgWEtZUXbhVE=
  template:
    metadata:
      name: feeder-uuid-secret
      namespace: adsb
    type: Opaque
