---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-credentials
  namespace: wireguard
spec:
  encryptedData:
    PASSWORD_HASH: AgAG0Fz2Rl0cbIANGqr+CRdvqO9uKoXsT5hI5x21C3vT73SXQQUQWH0dqVHKLt3zG/GTD9b9RrxtV0X4jfVKTorK1FnicjkAeFRkNKB7BVJLgSOEdSzCXSGjcHDKfVYIlxKmgyuil49eyjC9RQQEuhZMOEBMg3MJ0Tko6yqdVw4VOIt8gMWK/zNf2AD1NlLJtWYSF7bTKNfJZT2xFTy+JSSjvE1PMdkPjM8SbBa7Iv6ix9Pf4mYQNczDHocwNzwpjKkuHhEg/DYHrJXgxPZZIwPN1G/ZN6W1mRoGAVHpamjD/AXVSRscUq3cMrRCumYpi1hMiYGLtGjsm2aGC5Ot7gC0ojxRzZR0Oup5PF1wtTAIhtIq92os8vommoNx7p6QJqPLzwSqwBLtHrGKLEKpfgyLtDCJWd7OetLxnk7oaDSoF7XxipNjZ2crhGR84Y7Zg4WxPIFAAxxBubHA1oOSMaZtWsilrphrnFOV/zqtJ1hX9bcKVqBwTboIMpnXGN5ImthNMah9vffM5b1pN+rMEYjMt8YLcMD98LgcwndTfxXZV6HCqFtw+e11a/RBd3OoxSPWRPYTPL8CJw+KQVYSWwSW2SPBtRjrXNw+FSCD7qWp7VFT5i0dLOC5DP9TBaeAEw/joPMezKaQnupDzspvfAMnrle3ImXlqbYCwWf/yqmjiSbfuM0ZvRPlEGzpzVgzbnbQee+HSIPgpYck8WgoGsP0XIEmVNKThCPSfTZ3xT2tSynkT6CpizalUPmgQWN4IoNiMqnsZpH8IkRSlLc=
  template:
    metadata:
      name: wireguard-credentials
      namespace: wireguard
    type: Opaque
