---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguardhome-sync-config
  namespace: external-services
data:
  adguardhome-sync.yaml: |
    cron: "* * * * *"
    runOnStart: true
    continueOnError: false

    # raspi5
    origin:
      url: http://192.168.2.16
      username: ${ADGUARD_USERNAME}
      password: ${ADGUARD_PASSWORD}

    replicas:
      # macmini
      - url: http://192.168.2.4
        username: ${ADGUARD_USERNAME}
        password: ${ADGUARD_PASSWORD}

    api:
      port: 8080
      darkMode: true

    features:
      generalSettings: true
      queryLogConfig: true
      statsConfig: true
      clientSettings: true
      services: true
      filters: true
      # DHCP macht der UniFi-Controller, nicht AdGuard.
      dhcp:
        serverConfig: false
        staticLeases: false
      dns:
        serverConfig: true
        accessLists: true
        rewrites: true
