---
apiVersion: v1
kind: Service
metadata:
  name: adguard-macmini
  namespace: external-services
  annotations:
    homelab.io/expose: "internal"
    homelab.io/host: "adguard-macmini.elmstreet79.de"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard-macmini
  namespace: external-services
subsets:
  - addresses:
      - ip: 192.168.2.4
    ports:
      - name: http
        port: 80
        protocol: TCP
