apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
  - dreambox-service.yaml
  - plex-service.yaml
  - proxmox-service.yaml
  - unifi-service.yaml
  - unifi-nas-service.yaml
  - external-ingressroutes.yaml
  - apex-redirect.yaml
