apiVersion: v1
kind: Service
metadata:
  name: training-engine-frontend
  namespace: training-engine
  labels:
    app.kubernetes.io/name: training-engine-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: training-engine-frontend
