---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: training-engine
spec:
  encryptedData:
    .dockerconfigjson: AgCPIyuR65jykF5JYQjbCnl4rhjJXrHDgSqx8tv+tm5h0CWtI1ka+oR/oAmdkuVFZOFO9NXkrwe9//an+8W2biQMnpbNL+kh1zbwyDAX1JoOMvH4HsRadcH3p4zrH0IIN/t8bLuDP8KUalNPN1C5B5nErVLMRIk/WJ9j0RCa04U0gi9H8xKUHKRRrw1fswmMVkjdJ0tIWT3GKo5jI43ipZxG1XicXUqqvisQFayfU58JQs4p3o6AS9imMOS+aZyQZ1dcdzlX36M7Vn9nrr1lSYFbvA+XCvI2KDzxyxsfqlLchea+EFowUyTOngL+M9df5ImueSwoQSSd696Lat8FdgSzTeTQuLhdUSjozhjv9D6WOLEEaGZuOaCWuiLmOKA9jxy+YZmCFayqGfYaMnTRE7fCtTRlYLvWMk79Twf+WvXm1abAtep5L323qXFKuVOuZsDhFppLZ83F/hGniNxUyqXSi9mpx426pQmMK3+E1Z2NhzDZo8y7Z/cv32Xmdn3zP281A17P1IzPpaMM3oqLe97Uoj5qf+cotXFXUpQbYZ8PhrQm7FBxE2f+TsvCohDDYhzrHgo41j+Y4U7R2uvXfE69rDWCmkqezvaMRSv2Vt1NseETci8rItuoENF7Vu8du7OyyJTe0lGfmr8cHGuRcuhQzNoy//CnKOQZPPfR0aHP9Xb4wJ4U6kHjCFLnPua4AhZvFtgWFvD+1BTBsx4vOcxvsCFcnQL3u+ypOdKjymIpNcHza4pZTr4iAZAysJFZcRvY9Vbxrj5CTVjQV1MZR5A0LxK8H0nO9BjCTq30wH8pNdOSoiStck854yh24WmYfhA4kYDByDU5ReTmgw2jij5QY2Kn4RYdCplp6qgTqJ8kFa0BgfaliKTUTpI=
  template:
    metadata:
      name: ghcr-credentials
      namespace: training-engine
    type: kubernetes.io/dockerconfigjson
