apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: training-engine

resources:
  - namespace.yaml
  - secret-sealed.yaml
  - ghcr-secret-sealed.yaml
  - postgresql-pvc.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
